insert into sections (chairperson, venue_id, conferences_id, name) values ('Ardella Cannon', 77, 29, 'Executive Coaching');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Pedro Lamp', 31, 19, 'Professionalism');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Mordecai Bengtson', 85, 18, 'Women in Leadership');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Phillipp Avramovic', 11, 1, 'Brand Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Alair MacDaid', 76, 18, 'Employee Performance');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Nanette Forder', 93, 16, 'Productivity');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Dianemarie Dumbelton', 59, 17, 'Change Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Maxy Ander', 16, 17, 'Mindfulness');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Valeda Stichall', 73, 18, 'Employee Wellness');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Andeee Frenzel;', 99, 46, 'Emotional Intelligence');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Garnet Roddam', 58, 37, 'Employee Succession Planning');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Cassandre Daborne', 56, 34, 'Employee Performance Analysis');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Chevalier Gossipin', 20, 5, 'Employee Career Planning');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Cort Lorie', 63, 19, 'Cultural Awareness');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Randi Ledes', 80, 40, 'Business Writing');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Kerwinn Crosskell', 84, 35, 'Brand Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Collete Danielsky', 52, 30, 'Diversity and Inclusion');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Jennine Blissitt', 50, 4, 'Employee Performance Management Tools');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Husein Franca', 12, 12, 'Employee Mental Health');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Philis Claque', 53, 2, 'Employee Performance Monitoring');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Jess Harmes', 29, 29, 'Brand Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Abelard Jerrolt', 1, 22, 'Sales Skills');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Vivian Norgan', 46, 34, 'Employee Conflict Resolution');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Felisha Urey', 94, 9, 'Employee Work-Life Balance');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Tisha Coche', 37, 18, 'Presentation Skills for Technical Professionals');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Lura Condie', 37, 1, 'Career Development');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Jennie Ellison', 76, 5, 'Employee Onboarding');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Maximilien Helks', 18, 50, 'Public Speaking');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Hort Gilbane', 23, 29, 'Crisis Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Jori Klyn', 26, 39, 'Operations Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Nerti McKern', 27, 25, 'Employee Performance Monitoring');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Egbert Pattisson', 22, 3, 'Employee Feedback');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Aldon Miche', 26, 9, 'Business Planning');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Lorenza Ivashin', 76, 13, 'Artificial Intelligence');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Quincey Charrier', 11, 12, 'Operations Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Syman Saurat', 35, 34, 'Artificial Intelligence');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Fitz Kuzemka', 41, 24, 'Human Resource Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Hanna Bortolozzi', 14, 47, 'Employee Feedback');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Arlee Billinge', 1, 32, 'Employee Onboarding');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Carlyn Petrie', 89, 48, 'Employee Engagement');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Nert Ivanyushkin', 95, 46, 'Employee Engagement');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Zed Mandy', 70, 20, 'Employee Communication');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Anet Rainton', 27, 22, 'Supply Chain Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Jayme Ricardon', 29, 6, 'Investment Planning');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Elene Burdis', 19, 49, 'Employee Feedback');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Clari Howells', 79, 21, 'Financial Planning');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Ikey Fellgett', 46, 49, 'Employee Goal Setting');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Cayla Bartali', 39, 20, 'Customer Relationship Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Ian Mixture', 22, 28, 'Employee Succession Planning');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Easter Cowins', 99, 49, 'Human Resource Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Ardys Avramovitz', 7, 24, 'Succession Planning');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Marcy Hucke', 40, 20, 'Employee Retention');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Kimball Maile', 2, 43, 'Employee Performance Monitoring');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Demott Reven', 47, 4, 'Employee Benefits');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Guinna Howlin', 39, 10, 'Creative Thinking');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Erwin Bullivent', 9, 44, 'Employee Performance Monitoring');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Phyllida Digman', 98, 1, 'Business Planning');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Gracia Fishburn', 95, 26, 'Employee Performance Coaching');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Steffane Aspden', 15, 4, 'Operations Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Harriette Adshead', 34, 28, 'Critical Thinking');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Riane Skelhorn', 9, 10, 'Project Management for Non-Project Managers');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Raynell Mannooch', 54, 9, 'Environmental Sustainability');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Melina Brandsen', 5, 27, 'Productivity');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Ealasaid Byllam', 35, 46, 'Product Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Murray Coopman', 72, 42, 'Business Process Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Rutger Struan', 57, 49, 'Customer Experience');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Midge Apfelmann', 14, 35, 'Employee Motivation');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Romeo Snugg', 31, 3, 'Employee Feedback');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Dawn Tweedle', 75, 41, 'Crisis Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Rex Burgin', 20, 22, 'Effective Communication');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Shep Gwilt', 76, 11, 'Employee Conflict Resolution');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Nero Weaben', 93, 5, 'Employee Career Planning');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Sandy Antonucci', 81, 48, 'Employee Performance Monitoring');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Dacia Reedick', 38, 20, 'Customer Experience');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Shayna Saldler', 28, 43, 'Cybersecurity');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Willie Blackaller', 33, 26, 'Negotiation Skills');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Salomone Fatkin', 53, 37, 'Supply Chain Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Rafaelia Toman', 51, 20, 'Employee Performance Appraisal');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Haley Bulfoy', 27, 17, 'Business Writing');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Dayle McGowing', 97, 45, 'Critical Thinking');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Wake Arnaudet', 89, 23, 'Digital Marketing');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Angelina Scoggans', 76, 22, 'Women in Leadership');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Bernette Kingswood', 2, 7, 'Employee Performance Management Tools');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Maurene Eagleston', 9, 34, 'Employee Performance Management Software');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Briana Aylin', 95, 8, 'Data Analytics');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Laura Ferney', 33, 27, 'Digital Marketing');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Andras Stuchburie', 47, 26, 'Public Speaking');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Gillian Vann', 29, 11, 'Time Management for Managers');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Buddie Andor', 24, 26, 'Business Planning');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Austen MacGoun', 69, 3, 'Creative Thinking');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Martelle Chancellor', 29, 21, 'Social Media Marketing');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Floria Mil', 20, 10, 'Employee Retention');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Elmo Seebert', 91, 36, 'Operations Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Rina Verillo', 47, 33, 'High-Performance Team');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Constantina Walkey', 92, 41, 'Employee Performance Coaching');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Raina Arundell', 83, 6, 'Employee Performance Monitoring');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Anna-maria Baunton', 78, 24, 'Critical Thinking');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Hillard Bilson', 9, 18, 'Sales Management');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Grethel Beal', 29, 35, 'Employee Communication');
insert into sections (chairperson, venue_id, conferences_id, name) values ('Thaxter De Coursey', 68, 36, 'Customer Service');
