insert into venues (name, address) values ('Zoomcast', '00451 Harbort Terrace');
insert into venues (name, address) values ('Eazzy', '102 Bunker Hill Hill');
insert into venues (name, address) values ('Rhynyx', '12512 Cardinal Point');
insert into venues (name, address) values ('Eare', '980 Petterle Street');
insert into venues (name, address) values ('DabZ', '106 Hanson Trail');
insert into venues (name, address) values ('Rhyzio', '55 Bartillon Terrace');
insert into venues (name, address) values ('Blognation', '552 Macpherson Point');
insert into venues (name, address) values ('Pixonyx', '008 Stephen Court');
insert into venues (name, address) values ('Linkbridge', '9 Bultman Avenue');
insert into venues (name, address) values ('Oba', '52 Stephen Avenue');
insert into venues (name, address) values ('Feedfish', '02335 Jana Crossing');
insert into venues (name, address) values ('Jaxnation', '437 Bartillon Point');
insert into venues (name, address) values ('Cogibox', '98 Homewood Alley');
insert into venues (name, address) values ('Dynava', '0 Florence Point');
insert into venues (name, address) values ('Eamia', '2335 Washington Park');
insert into venues (name, address) values ('Jatri', '92 Milwaukee Place');
insert into venues (name, address) values ('Jaxbean', '711 Pearson Point');
insert into venues (name, address) values ('Zoomcast', '53 Myrtle Point');
insert into venues (name, address) values ('Jabbersphere', '875 Heath Terrace');
insert into venues (name, address) values ('Quire', '716 Forest Place');
insert into venues (name, address) values ('Ozu', '936 Briar Crest Point');
insert into venues (name, address) values ('Tazz', '9 Hovde Avenue');
insert into venues (name, address) values ('Blogtag', '610 Arapahoe Lane');
insert into venues (name, address) values ('Dynabox', '1817 Manley Pass');
insert into venues (name, address) values ('Twiyo', '822 Katie Junction');
insert into venues (name, address) values ('Fliptune', '8 Melody Park');
insert into venues (name, address) values ('Twiyo', '30 Alpine Center');
insert into venues (name, address) values ('Buzzshare', '33 Weeping Birch Center');
insert into venues (name, address) values ('Topdrive', '904 Clove Parkway');
insert into venues (name, address) values ('Omba', '2 Texas Street');
insert into venues (name, address) values ('Gigaclub', '80427 Loomis Center');
insert into venues (name, address) values ('Dabshots', '29079 Gulseth Court');
insert into venues (name, address) values ('Skinder', '19 Kennedy Avenue');
insert into venues (name, address) values ('Trilith', '11 Golf Course Drive');
insert into venues (name, address) values ('Eare', '418 Havey Place');
insert into venues (name, address) values ('Photojam', '9249 Old Gate Point');
insert into venues (name, address) values ('Meetz', '143 Thierer Crossing');
insert into venues (name, address) values ('Yakitri', '3 Cottonwood Road');
insert into venues (name, address) values ('Tagtune', '36 Jenifer Parkway');
insert into venues (name, address) values ('Flashspan', '669 Scofield Alley');
insert into venues (name, address) values ('Jetpulse', '25311 Toban Place');
insert into venues (name, address) values ('Dabtype', '11290 Carey Alley');
insert into venues (name, address) values ('Bubbletube', '63560 Spohn Point');
insert into venues (name, address) values ('Edgeblab', '02 Carey Street');
insert into venues (name, address) values ('Thoughtstorm', '3352 Vermont Court');
insert into venues (name, address) values ('Twinte', '718 Johnson Terrace');
insert into venues (name, address) values ('Yambee', '7396 Marquette Park');
insert into venues (name, address) values ('Meevee', '68 Mockingbird Parkway');
insert into venues (name, address) values ('Fatz', '39078 Bartillon Pass');
insert into venues (name, address) values ('Janyx', '5 Cody Hill');
insert into venues (name, address) values ('Lazzy', '4 Saint Paul Point');
insert into venues (name, address) values ('Quinu', '017 Continental Alley');
insert into venues (name, address) values ('Agimba', '7140 Stang Terrace');
insert into venues (name, address) values ('Eamia', '0197 Debs Circle');
insert into venues (name, address) values ('Flashset', '33 Stuart Hill');
insert into venues (name, address) values ('Flashpoint', '638 Welch Circle');
insert into venues (name, address) values ('Devshare', '6 Anniversary Alley');
insert into venues (name, address) values ('Devbug', '2725 Grasskamp Center');
insert into venues (name, address) values ('Twimm', '3297 Washington Plaza');
insert into venues (name, address) values ('Kazu', '2432 Longview Parkway');
insert into venues (name, address) values ('Feedfish', '360 Schiller Trail');
insert into venues (name, address) values ('Kanoodle', '7250 Bultman Place');
insert into venues (name, address) values ('Kayveo', '79757 Buhler Park');
insert into venues (name, address) values ('Pixoboo', '91421 New Castle Park');
insert into venues (name, address) values ('Avamm', '9 Lake View Point');
insert into venues (name, address) values ('Voonix', '40 Westerfield Trail');
insert into venues (name, address) values ('Skiba', '2 Stone Corner Parkway');
insert into venues (name, address) values ('Youspan', '20147 Spenser Crossing');
insert into venues (name, address) values ('Brainbox', '9 Schmedeman Hill');
insert into venues (name, address) values ('Feedfire', '39 Nevada Road');
insert into venues (name, address) values ('Skinder', '0 Pleasure Avenue');
insert into venues (name, address) values ('Divanoodle', '846 Fairview Hill');
insert into venues (name, address) values ('Blogspan', '11191 Dryden Terrace');
insert into venues (name, address) values ('Voomm', '946 Hauk Trail');
insert into venues (name, address) values ('Jazzy', '51153 Stoughton Pass');
insert into venues (name, address) values ('Tavu', '955 Westridge Way');
insert into venues (name, address) values ('Tagfeed', '94 Green Junction');
insert into venues (name, address) values ('Zoonder', '5944 Norway Maple Pass');
insert into venues (name, address) values ('Zoovu', '594 Meadow Ridge Crossing');
insert into venues (name, address) values ('Minyx', '2679 Rieder Lane');
insert into venues (name, address) values ('Kayveo', '320 Carpenter Alley');
insert into venues (name, address) values ('Devcast', '87913 International Trail');
insert into venues (name, address) values ('Avaveo', '54 John Wall Park');
insert into venues (name, address) values ('Mydeo', '32 Starling Crossing');
insert into venues (name, address) values ('Yabox', '140 2nd Place');
insert into venues (name, address) values ('Skimia', '513 Novick Drive');
insert into venues (name, address) values ('Dabfeed', '4383 Clarendon Point');
insert into venues (name, address) values ('Meedoo', '64807 Sheridan Crossing');
insert into venues (name, address) values ('Kwideo', '9481 Burning Wood Park');
insert into venues (name, address) values ('Fatz', '88 Reindahl Park');
insert into venues (name, address) values ('Ooba', '0728 Huxley Junction');
insert into venues (name, address) values ('Quire', '12 Messerschmidt Center');
insert into venues (name, address) values ('Aibox', '3493 Bay Avenue');
insert into venues (name, address) values ('Avaveo', '9121 Sherman Hill');
insert into venues (name, address) values ('Blogtags', '041 Fieldstone Place');
insert into venues (name, address) values ('Photospace', '4 Delaware Road');
insert into venues (name, address) values ('Brainverse', '0718 Graceland Court');
insert into venues (name, address) values ('Jabbersphere', '5 Union Way');
insert into venues (name, address) values ('Twitternation', '37 Burrows Center');
insert into venues (name, address) values ('Wikibox', '5288 Truax Park');

